In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
a=np.array(list1)
a

array([1, 2, 3])

In [3]:
print(a.shape)

(3,)


In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)

(2, 4)


In [5]:
print(b[0,0])

1


In [7]:
print(type(b))

<class 'numpy.ndarray'>


In [8]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
a = np.array([1,2.3,3,4])
print(a)

[1.  2.3 3.  4. ]


In [10]:
a = np.array([1,'2','3',4])
print(a)

['1' '2' '3' '4']


In [11]:
a = np.array([1, 2,'3',4])
print(a)

['1' '2' '3' '4']


In [13]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4],[1,2,3,4]])
a3 = np.array([[[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3]]])

In [14]:
a1

array([1, 2, 3, 4, 5])

In [15]:
a2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [16]:
a3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [17]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [20]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(5,)
(2, 4)
(3, 2, 3)


In [23]:
a = np.zeros((3),dtype='int64')
print(a)

[0 0 0]


In [24]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [25]:
a = np.zeros((2,2,2),dtype='int64')
print(a)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [26]:
a = np.ones((3))
print(a)

[1. 1. 1.]


In [29]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
a = range(0,10,2)
a

range(0, 10, 2)

In [32]:
print(list(a))

[0, 2, 4, 6, 8]


In [33]:
print(np.arange(0,10,2))
print(a)

[0 2 4 6 8]
range(0, 10, 2)


In [36]:
print(np.array(range(12)).reshape((3,4)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
a = np.array(range(12)).reshape((3,-1))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
a = np.array(range(12)).reshape((-1,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a = arr[0:2,0:2]
a

array([[1, 2],
       [4, 5]])

In [44]:
a = arr[1:,1:]
a

array([[5, 6],
       [8, 9]])

In [51]:
a = np.array([0,1,2,3])
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [52]:
print(a[1:4:2])

[1 3]


In [53]:
print(a[::-1])

[3 2 1 0]


In [54]:
a[1:4:2]

array([1, 3])

In [55]:
print(b[0][1])

1


In [56]:
print(b[0,1])

1


In [57]:
print(b[:2])

[[0 1 2 3]
 [4 5 6 7]]


In [58]:
print(b[:,0])

[0 4 8]


In [59]:
print(b[0,:])

[0 1 2 3]


In [60]:
print(b[[0,2],:])

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [61]:
print(b[[2,0], :])

[[ 8  9 10 11]
 [ 0  1  2  3]]


In [62]:
b_5 = b > 5
print(b_5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [64]:
print(b[b_5])

[ 6  7  8  9 10 11]


In [65]:
print(b[[0,1],[1,2]])

[1 6]


In [66]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print('---------------')
print(c)

[0 1 2 3]
---------------
[0 1 2 3]


In [73]:
a = [0,1,2,3]
a = [0,1,2,3]
print(a+b)

[0, 1, 2, 3, 0, 1, 2, 3]


In [75]:
d = [0,0,0,0]
for i in range(len(a)):
    d[i] = a[i] + b[i]

print(d)

[0, 2, 4, 6]


In [77]:
a = np.array([0,1,2,3])
c = np.arange(4)
print(a)
print(c)
print(a + c)

[0 1 2 3]
[0 1 2 3]
[0 2 4 6]


In [79]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [82]:
np.split(a,(1,3)) # [:1],[1:3],[3:]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [84]:
splite1, splite2 = np.hsplit(a,2)
print('splite1'); print(splite1)

splite1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [87]:
print('splite2'); print(splite2)

splite2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [85]:
np.split(a,2,axis = 1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [86]:
np.split(a,(1,3), axis= 1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [90]:
splite1, splite2 = np.vsplit(a,2)

In [91]:
print('splite1'); print(splite1)

splite1
[[0 1 2 3]
 [4 5 6 7]]


In [92]:
print('splite2'); print(splite2)

splite2
[[ 8  9 10 11]
 [12 13 14 15]]


In [94]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
stack0 = np.stack((a,a))
print(stack0.shape)

(2, 4, 4)


In [96]:
print(stack0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [97]:
stack1 = np.stack((a,a),axis=1)
print(stack1.shape)

(4, 2, 4)


In [98]:
print(stack1)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]


In [99]:
print(np.vstack((a,a)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [100]:
print(np.hstack((a,a)))

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


In [102]:
a = np.arange(9).reshape(3,3)
b = 2 * a
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [103]:
print(np.hstack((a,b)))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [106]:
print(np.concatenate((a,b) ,axis=1))

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]


In [107]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [110]:
c = a.ravel()
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [113]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [114]:
print(a+b)

[5 7 9]


In [115]:
print(np.add(a, b))

[5 7 9]


In [116]:
print(a * b)

[ 4 10 18]


In [118]:
print(np.multiply(a, b))

[ 4 10 18]


In [119]:
lst1 = [[1,2],[3,4]]
lst2 = [[1,2],[3,4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a,b)
print(c)

[[ 7 10]
 [15 22]]


In [120]:
a = np.array([[1,2],[3,4]])
s = np.sum(a,axis=0)
print(s)

[4 6]


In [121]:
s = np.sum(a, axis=1)
print(s)

[3 7]


In [122]:
s = np.prod(a)
print(s)

24


In [123]:
s = np.prod(a,axis=0)
print(s)

[3 8]


In [124]:
s= np.prod(a,axis=1)
print(s)

[ 2 12]


In [128]:
np.random.seed(0)
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [130]:
x = np.arange(10)
print(x)
print('-------------------------')
np.random.seed(0)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
-------------------------
[2 8 4 9 1 6 7 3 0 5]


In [135]:
z = np.random.choice(np.arange(5), 3, replace=False)
print(z)

[2 4 1]


In [136]:
z = np.random.choice(5, 10, p = [0.1,0,0.3,0.6,0])
print(z)

[2 3 3 3 3 3 3 3 3 3]


In [138]:
x = np.random.randint(1,100,size=5)
print(x)

[29 35  1  1 37]


In [139]:
a = [5,1,7,7,2,3,5]
x = np.unique(a)
print(x)

[1 2 3 5 7]


In [140]:
x, cnt = np.unique(a, return_counts=True)
print(x, cnt, sep=",")

[1 2 3 5 7],[1 1 1 2 2]


In [147]:
x = np.array([18,5,10,23,19,-8,10,0,0,5,2])
print(len(x))
print(sum(x))
print(np.size(x))
print(np.sum(x))
print(np.mean(x))
print(np.var(x))
print(np.std(x))
print(np.max(x))
print(np.min(x))
print(np.median(x))
print(np.sort(x))

11
84
11
84
7.636363636363637
80.9586776859504
8.997704023024452
23
-8
5.0
[-8  0  0  2  5  5 10 10 18 19 23]
